
name: Build Blocks Stafn APK

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build APK
        uses: ArtemSBulgakov/buildozer-action@master
        with:
          command: buildozer android debug
          workdir: .
          docker_image: ghcr.io/kivy/buildozer:latest

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Blocks-Stafn-APK
          path: bin/*.apk
